In [5]:
import numpy as np

In [ ]:
 1. What is a Python library? Why do we use Python libraries?

In [ ]:
A Python library is a collection of related modules. It contains bundles of code that can be used repeatedly in different programs. It makes Python Programming simpler and convenient for the programmer. As we don’t need to write the same code again and again for different programs.
It is a widely used, object-oriented, open-source, high-performance programming language with many advantages – one of which is the extensive availability of libraries in Python. Libraries written in Python play a critical role in machine learning and data science. Each module in a Python library serves a specific purpose.

In [ ]:
 2. What is the difference between Numpy array and List?

In [ ]:
Difference between Numpy array and Python List are given below

                Numpy Array                                    |                      Python List
1.It doesnot  store additional information about each element. | 1.Lists in Python store additional information about each element.
                                                               |
2.It cannot hold different data types.                         | 2.Lists can hold different data types.
                                                               | 
3.Itt store elements in contiguous memory locations.           | 3.Lists may not store elements in contiguous memory locations.
                                                               | 
4.Numpy array is more optimized for numerical computationss.   | 4.Lists are not optimized for numerical computations and may have slower mathematical operations due to Python’s interpretation overhead. 
                                                               |
5.Numpy array has extra metadata as shape,strides,and data type| 5. It doesnot have extra metadata. 
                                                               |
    
                                                                
                                                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                                                                

In [ ]:
3. Find the shape, size and dimension of the following array?
 [[1, 2, 3, 4]
 [5, 6, 7, 8],
 [9, 10, 11, 12]]

In [102]:
arr1= np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [103]:
np.size(arr1)

12

In [104]:
np.ndim(arr1)

2

In [105]:
np.shape(arr1)

(3, 4)

In [ ]:
4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
 [5, 6, 7, 8],
 [9, 10, 11, 12]]

In [106]:
arr2 =np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [107]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Ans:-

In [16]:
arr2[ 0,0:4]

array([1, 2, 3, 4])

In [ ]:
 5. How do you access the element at the third row and fourth column from the given numpy array?
 [ [1, 2, 3, 4]
 [5, 6, 7, 8],
 [9, 10, 11, 12]]

In [ ]:
Answer:-

In [20]:
arr2[2][3]

12

In [ ]:
6. Write code to extract all odd-indexed elements from the given numpy array?

In [ ]:
Ans:-

In [30]:
np.extract(arr2%2 !=0,arr2)

array([ 1,  3,  5,  7,  9, 11])

               Or 

In [29]:
odd_elements = arr2[arr2 % 2 == 1]

print(f"Odd-indexed elements: {odd_elements}")

Odd-indexed elements: [ 1  3  5  7  9 11]


In [ ]:
 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [ ]:
Ans :-

In [49]:
Random_matrix = np.random.random((3,3))

In [50]:
Random_matrix

array([[0.87560018, 0.89342016, 0.30520091],
       [0.73711871, 0.44649629, 0.20155574],
       [0.2406117 , 0.06084186, 0.16639821]])

In [ ]:
8. Describe the difference between np.random.rand and np.random.randn?

In [ ]:
np.random.rand creates an array of the given shape and populate it with random samples from a uniform distribution over [0, 1). 
 
Exp:-                   
                                                                                                                         

In [55]:
np.random.rand(2,2)

array([[0.51441006, 0.65381058],
       [0.48713444, 0.68732894]])

In [ ]:
while np.random.randn creates an array of the given shape and populate it with random samples from a normal distribution with a specific mean and standard deviation.

Exp:-

In [60]:
np.random.randn(2,2)

array([[-1.76942914, -0.66798011],
       [-0.37386673,  1.21665565]])

In [ ]:
9. Write code to increase the dimension of the following array?
 [[1, 2, 3, 4]
 [5, 6, 7, 8],
 [9, 10, 11, 12]]

In [ ]:
Ans :-

In [61]:
arr3=np.expand_dims(arr1, axis = 1)

In [62]:
arr3

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [63]:
arr4=np.expand_dims(arr1, axis = 0)

In [64]:
arr4

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [ ]:
10. How to transpose the following array in NumPy?
 [[1, 2, 3, 4]
 [5, 6, 7, 8],
 [9, 10, 11, 12]]

In [ ]:
Ans :-

In [67]:
arr5=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [68]:
arr5.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
11. Consider the following matrix:
Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
 
 Perform the following operation using Python:
1.Index wise multiplicatio
2.Matrix multiplication
3.Add both the matrices
4.Subtract matrix B from A
5.Divide Matrix B by A

In [71]:
Arr6 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
Arr7 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [72]:
Arr6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [73]:
Arr7

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [74]:
Arr6*Arr7

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [75]:
Arr6@Arr7

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [76]:
Arr6@Arr7.T

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [77]:
Arr6+Arr7

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [78]:
Arr6-Arr7

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [79]:
Arr6/Arr7

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
12.  Which function in Numpy can be used to swap the byte order of an array?
 

In [ ]:
Ans :-

In [ ]:
ndarray.byteswap() function is used in numpty for swapping the byte order.

In [89]:
Arr8 = np.array([1,2,3], dtype =  np.int16)

In [90]:
print(Arr8.byteswap(True))

[256 512 768]


In [ ]:
13.  What is the significance of the np.linalg.inv function?
 

In [ ]:
Ans:- It is used to find the inverse of anon-singular matrix using numpy library.

Exp:-

In [91]:
Arr9 = np.diag([1,3,4])

In [92]:
Arr9

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [93]:
np.linalg.inv(Arr9)

array([[1.        , 0.        , 0.        ],
       [0.        , 0.33333333, 0.        ],
       [0.        , 0.        , 0.25      ]])

In [ ]:
14. What does the np.reshape function do, and how is it used?

In [ ]:
Ans :- np.reshape() is used to reshape the dimension of  array but size of array doesnot changes just dimension of array changes.
Exp :- 

In [94]:
Arr10 = np.array([[1,2],[3,4]])

In [96]:
Arr10

array([[1, 2],
       [3, 4]])

In [95]:
Arr10.reshape(1,4)

array([[1, 2, 3, 4]])

In [97]:
Arr10.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
15. What is broadcasting in Numpy?

In [99]:
Arr11 = np.zeros((3,3))

In [100]:
Arr11

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [101]:
Arr11 +5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])